AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket
    BucketName: 's3demo-codepipeline-s3bucket-9gi5hflbqiac'
Properties:    
    VersioningConfiguration: 
      Status: 'Enabled'
